# Generated by Django 5.2.7 on 2025-10-19 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='fecha_de_creacion',
        ),
    ]
